### ISSUE TITLE
"File name too long" in sbt

### ISSUE THREAD

**Issue by 3100** [ucb-bar/chisel-tutorial#114]
Hi, I got an error when trying to run the first example written in README. The branch is the latest `release`.

```
$ sbt
[info] Loading project definition from /home/sato/chisel-tutorial/project
[info] Set current project to chisel-tutorial (in build file:/home/sato/chisel-tutorial/)
> test:run-main problems.Launcher Mux2
[info] Compiling 56 Scala sources to /home/sato/chisel-tutorial/target/scala-2.11/classes...
[info] Compiling 63 Scala sources to /home/sato/chisel-tutorial/target/scala-2.11/test-classes...
[error] ファイル名が長すぎます
[error] one error found
[error] (test:compileIncremental) Compilation failed
[error] Total time: 20 s, completed 2018/02/08 15:25:38
```
("ファイル名が長すぎます" means "File name too long".)

As a temporary fix, I changed `build.sbt` and add another line and it seems to be working:

```
scalacOptions ++= Seq("-Xmax-classfile-name","140")
```

Is there any better solution for this issue?

**Comment by ucbjrl** [comment]
I suspect this error is due to the particulars of your locale - we don't see this error in our testing. You could create (or add to) a ` ~/.sbt/0.13/global.sbt` file with this content:
```scala
scalacOptions in Global ++= Seq("-Xmax-classfile-name","140")
```
You'll probably want to copy that file to `~/.sbt/1.0/global.sbt`, and presumably to `~/.sbt/1.1/global.sbt` when version 1.1.x of sbt becomes popular.

**Comment by 3100** [comment]
@ucbjrl Thank you for your idea. I'll use `global.sbt` instead of modifying `build.sbt`.
