### ISSUE TITLE
java.lang.Runtimeexception

### ISSUE THREAD

**Issue by jjtoms4s** [ucb-bar/chisel-tutorial#129]
![360 20180528152044939](https://user-images.githubusercontent.com/39576165/40602560-9b3fafac-628b-11e8-814c-b3431aa392a4.jpg)
i follow the quick_start and then i run into this error when run this command ( test:run-main problems.Launcher Mux4) does anyone have idea

**Comment by jjtoms4s** [comment]
in addtions the MUX2 work but the other task run into the same error

**Comment by ucbjrl** [comment]
The README.md was out of date for the updated `sbt`. We've updated it to specify the correct invocation for running tests.

Additionally, the initial `problems` tests are expected to generate errors, and we force an early exit with a non-zero exit code to indicate failure (the tests will fail until you add the correct code to make them pass). The updated `sbt` was throwing a security exception in response to this attempt to exit early.

Fixed by #125 and #131.
